# === WatonesCallarRegistroVoiceChat ===

# Grupo de LuckPerms que se aplica al jugador para silenciarlo en voice chat (debes crearlo en LP)
group_name: "mutevoice"

# URL del webhook de Discord
webhook_url: "https://discord.com/api/webhooks/XXXX/XXXX"

# Nombre de la modalidad (placeholder {modality})
modality_name: "Survival"

# Anti-spam por jugador (ms) para evitar ráfagas de webhooks
rate_limit_ms_per_target: 1500

# Mensajes en el juego (&-colors)
messages:
  prefix: "&4&lWATONES &8| &r"
  usage_callar: "&cUso: &7/callar <jugador>"
  usage_descallar: "&cUso: &7/descallar <jugador>"
  muted: "&a✔ Jugador &f%target% &amuteado en voice chat por &e1 día&a."
  unmuted: "&a✔ Mute de voice chat retirado de &f%target%&a."
  no_perm: "&cNo tienes permiso."
  not_found: "&cNo encontré al jugador &f%target%&c."
  error: "&cOcurrió un error, intenta nuevamente."

# === Discord ===
discord:
  use_embeds: true

  # (Opcional) Nombre e icono del bot que publica el webhook
  username: "Moderación Watones"
  avatar_url: ""

  # Si use_embeds=false, se usa este template de texto plano
  # Placeholders: {action},{staff},{target},{duration},{timestamp},{modality}
  content_template: "**[{action}]** Staff: {staff} → Jugador: {target} (duración: {duration}) • {modality} • {timestamp}"

  # Config de embed (si use_embeds=true)
  embed:
    title: "Voice Chat {action}"
    description: "Registro de moderación • Modalidad: {modality}"
    # Color (HEX '#RRGGBB' o INT)
    color: "#FF0044"
    footer: "Watones • {timestamp}"
    fields:
      - name: "Acción"
        value: "{action}"
        inline: true
      - name: "Staff"
        value: "{staff}"
        inline: true
      - name: "Jugador"
        value: "{target}"
        inline: true
      - name: "Duración"
        value: "{duration}"
        inline: true
