name: Build Plugin
on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: watonescallarregistrovoicechat
          path: target/*.jar
